// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using PoliticasSettings.Datos;
using PoliticasSettings.Models;
using System;
using System.Collections.Generic;

namespace PoliticasSettings.Datos.Configurations
{
    public partial class PadreConfiguration : IEntityTypeConfiguration<Padre>
    {
        public void Configure(EntityTypeBuilder<Padre> entity)
        {
            entity.Property(e => e.Id).ValueGeneratedNever();

            entity.Property(e => e.Ocupacion)
                .HasMaxLength(50)
                .IsUnicode(false);

            entity.HasOne(d => d.IdPersonaNavigation)
                .WithMany(p => p.Padre)
                .HasForeignKey(d => d.IdPersona)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Padre_Persona");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Padre> entity);
    }
}
